pub(super) const PARAMETER_GROUP_ROOT_UUID: &str = "e9fe6eff-953b-4ce2-be7c-4a7c3913686b";
pub(super) const DEFORMER_ROOT_UUID: &str = "71fae776-e218-4aee-873e-78e8ac0cb48a";
pub(super) const FILTER_SELECTOR_UUID: &str = "5e9fe1ea-0ec3-4d68-a5fa-018fc7abe301";
pub(super) const FILTER_LAYER_UUID: &str = "4083cd1f-40ba-4eda-8400-379019d55ed8";

pub(super) const VERSION_INSTRUCTIONS: &[(&str, &str)] = &[
    ("CArtMeshSource", "4"),
    ("CRotationDeformerForm", "1"),
    ("KeyformGridSource", "1"),
    ("CParameterGroup", "4"),
    ("SerializeFormatVersion", "2"),
    ("CModelSource", "4"),
    ("CFloatColor", "1"),
    ("CLabelColor", "0"),
    ("CModelImage", "3"),
];

pub(super) const IMPORT_INSTRUCTIONS: &[&str] = &[
    "com.live2d.cubism.doc.model.ACForm",
    "com.live2d.cubism.doc.model.ACParameterControllableSource",
    "com.live2d.cubism.doc.model.CModelInfo",
    "com.live2d.cubism.doc.model.CModelSource",
    "com.live2d.cubism.doc.model.affecter.ACAffecterForm",
    "com.live2d.cubism.doc.model.affecter.ACAffecterSource",
    "com.live2d.cubism.doc.model.affecter.CAffecterSourceSet",
    "com.live2d.cubism.doc.model.affecter.glue.CGlueForm",
    "com.live2d.cubism.doc.model.affecter.glue.CGlueSource",
    "com.live2d.cubism.doc.model.deformer.ACDeformerForm",
    "com.live2d.cubism.doc.model.deformer.ACDeformerSource",
    "com.live2d.cubism.doc.model.deformer.CDeformerSourceSet",
    "com.live2d.cubism.doc.model.deformer.rotation.CRotationDeformerForm",
    "com.live2d.cubism.doc.model.deformer.rotation.CRotationDeformerSource",
    "com.live2d.cubism.doc.model.deformer.warp.CWarpDeformerForm",
    "com.live2d.cubism.doc.model.deformer.warp.CWarpDeformerSource",
    "com.live2d.cubism.doc.model.drawable.ACDrawableForm",
    "com.live2d.cubism.doc.model.drawable.ACDrawableSource",
    "com.live2d.cubism.doc.model.drawable.CDrawableSourceSet",
    "com.live2d.cubism.doc.model.drawable.ColorComposition",
    "com.live2d.cubism.doc.model.drawable.TextureState",
    "com.live2d.cubism.doc.model.drawable.artMesh.CArtMeshForm",
    "com.live2d.cubism.doc.model.drawable.artMesh.CArtMeshSource",
    "com.live2d.cubism.doc.model.extension.ACExtension",
    "com.live2d.cubism.doc.model.extension.editableMesh.CEditableMeshExtension",
    "com.live2d.cubism.doc.model.extension.meshGenerator.CMeshGeneratorExtension",
    "com.live2d.cubism.doc.model.extension.meshGenerator.MeshGenerateSetting",
    "com.live2d.cubism.doc.model.extension.textureInput.ACTextureInput",
    "com.live2d.cubism.doc.model.extension.textureInput.CTextureInputExtension",
    "com.live2d.cubism.doc.model.extension.textureInput.CTextureInput_ModelImage",
    "com.live2d.cubism.doc.model.extension.textureInput.CTextureInput_TextureAtlasRegion",
    "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.CLayerInputData",
    "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.CLayerSelectorMap",
    "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.ModelImageFilterEnv",
    "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.ModelImageFilterSet",
    "com.live2d.cubism.doc.model.id.CAffecterId",
    "com.live2d.cubism.doc.model.id.CDeformerId",
    "com.live2d.cubism.doc.model.id.CDrawableId",
    "com.live2d.cubism.doc.model.id.CParameterId",
    "com.live2d.cubism.doc.model.id.CPartId",
    "com.live2d.cubism.doc.model.interpolator.InterpolationType",
    "com.live2d.cubism.doc.model.interpolator.KeyOnParameter",
    "com.live2d.cubism.doc.model.interpolator.KeyformBindingSource",
    "com.live2d.cubism.doc.model.interpolator.KeyformGridAccessKey",
    "com.live2d.cubism.doc.model.interpolator.KeyformGridSource",
    "com.live2d.cubism.doc.model.interpolator.KeyformOnGrid",
    "com.live2d.cubism.doc.model.interpolator.extendedInterpolation.ExtendedInterpolationType",
    "com.live2d.cubism.doc.model.morphTarget.KeyFormMorphTargetSet",
    "com.live2d.cubism.doc.model.morphTarget.MorphTargetBlendWeightConstraintSet",
    "com.live2d.cubism.doc.model.options.edition.EditorEdition",
    "com.live2d.cubism.doc.model.param.CParameterSource",
    "com.live2d.cubism.doc.model.param.CParameterSource$Type",
    "com.live2d.cubism.doc.model.param.CParameterSourceSet",
    "com.live2d.cubism.doc.model.param.group.CParameterGroup",
    "com.live2d.cubism.doc.model.param.group.CParameterGroupSet",
    "com.live2d.cubism.doc.model.parts.CPartForm",
    "com.live2d.cubism.doc.model.parts.CPartSource",
    "com.live2d.cubism.doc.model.parts.CPartSourceSet",
    "com.live2d.cubism.doc.model.texture.CTextureManager",
    "com.live2d.cubism.doc.model.texture.textureAtlas.CTextureAtlas",
    "com.live2d.cubism.doc.model.texture.LayeredImageWrapper",
    "com.live2d.cubism.doc.model.texture.TextureImageGroup",
    "com.live2d.cubism.doc.model.texture.modelImage.CModelImage",
    "com.live2d.cubism.doc.model.texture.modelImage.CModelImageGroup",
    "com.live2d.cubism.doc.resources.ACImageLayer",
    "com.live2d.cubism.doc.resources.ACLayerEntry",
    "com.live2d.cubism.doc.resources.ACLayerGroup",
    "com.live2d.cubism.doc.resources.CLayer",
    "com.live2d.cubism.doc.resources.CLayerGroup",
    "com.live2d.cubism.doc.resources.CLayerIdentifier",
    "com.live2d.cubism.doc.resources.CLayeredImage",
    "com.live2d.cubism.doc.resources.LayerSet",
    "com.live2d.doc.CoordType",
    "com.live2d.graphics.CImageCanvas",
    "com.live2d.graphics.CImageResource",
    "com.live2d.graphics.cachedImage.CCachedImage",
    "com.live2d.graphics.cachedImage.CCachedImageManager",
    "com.live2d.graphics.cachedImage.CachedImageType",
    "com.live2d.graphics.filter.AValueConnector",
    "com.live2d.graphics.filter.FilterEnv",
    "com.live2d.graphics.filter.FilterEnv$EnvValueSet",
    "com.live2d.graphics.filter.FilterSet",
    "com.live2d.graphics.filter.FilterSet$EnvConnection",
    "com.live2d.graphics.filter.FilterValue",
    "com.live2d.graphics.filter.concreteConnector.EnvValueConnector",
    "com.live2d.graphics.filter.concreteConnector.FilterOutputValueConnector",
    "com.live2d.graphics.filter.filterInstance.FilterInstance",
    "com.live2d.graphics.filter.id.FilterInstanceId",
    "com.live2d.graphics.filter.id.FilterValueId",
    "com.live2d.graphics.psd.blend.ACBlend",
    "com.live2d.graphics.psd.blend.CBlend_Normal",
    "com.live2d.graphics3d.editableMesh.GEditableMesh2",
    "com.live2d.graphics3d.texture.Anisotropy",
    "com.live2d.graphics3d.texture.GTexture",
    "com.live2d.graphics3d.texture.GTexture$FilterMode",
    "com.live2d.graphics3d.texture.GTexture2D",
    "com.live2d.graphics3d.texture.MagFilter",
    "com.live2d.graphics3d.texture.MinFilter",
    "com.live2d.graphics3d.texture.WrapMode",
    "com.live2d.graphics3d.type.GVector2",
    "com.live2d.type.CAffine",
    "com.live2d.type.CAffecterGuid",
    "com.live2d.type.CColor",
    "com.live2d.type.CDeformerGuid",
    "com.live2d.type.CDrawableGuid",
    "com.live2d.type.CExtensionGuid",
    "com.live2d.type.CFloatColor",
    "com.live2d.type.CFormGuid",
    "com.live2d.type.CLayerGuid",
    "com.live2d.type.CLayeredImageGuid",
    "com.live2d.type.CModelGuid",
    "com.live2d.type.CModelImageGuid",
    "com.live2d.type.CParameterGroupGuid",
    "com.live2d.type.CParameterGuid",
    "com.live2d.type.CPartGuid",
    "com.live2d.type.CPoint",
    "com.live2d.type.CRect",
    "com.live2d.type.CSize",
    "com.live2d.type.CTextureAtlasGuid",
    "com.live2d.type.GEditableMeshGuid",
    "com.live2d.type.GTextureGuid",
    "com.live2d.type.StaticFilterDefGuid",
];
