mod writer;

pub(crate) use writer::{XmlWriter, attr};

pub(crate) const IMPORTS: &[&str] = &[
    "com.live2d.cubism.CETargetVersion$Animation",
    "com.live2d.cubism.doc.animation.CAnimation",
    "com.live2d.cubism.doc.animation.CSceneSource",
    "com.live2d.cubism.doc.animation.formAnimation.FormAnimationSet",
    "com.live2d.cubism.doc.animation.movie.core.CMvMovieInfo",
    "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_EyeBlink",
    "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_LipSync",
    "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_Live2DParameter",
    "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_Live2DPartsVisible",
    "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_VisualDefault",
    "com.live2d.cubism.doc.animation.movie.effect.CSoundHandler",
    "com.live2d.cubism.doc.animation.movie.effect.CVisualHandler",
    "com.live2d.cubism.doc.animation.movie.effect.ICMvEffect",
    "com.live2d.cubism.doc.animation.movie.effect.attr.CMvAttrF",
    "com.live2d.cubism.doc.animation.movie.effect.attr.ICMvAttr",
    "com.live2d.cubism.doc.animation.movie.effect.attr.value.ACValueSequence",
    "com.live2d.cubism.doc.animation.movie.effect.attr.value.CBezierCtrlPt",
    "com.live2d.cubism.doc.animation.movie.effect.attr.value.CBezierPt",
    "com.live2d.cubism.doc.animation.movie.effect.attr.value.CCurveType",
    "com.live2d.cubism.doc.animation.movie.effect.attr.value.CFrameIndexType",
    "com.live2d.cubism.doc.animation.movie.effect.attr.value.CMutableSequence",
    "com.live2d.cubism.doc.animation.movie.effect.attr.value.CSeqPt",
    "com.live2d.cubism.doc.animation.movie.res.CResourceData",
    "com.live2d.cubism.doc.animation.movie.res.CResourceGroup",
    "com.live2d.cubism.doc.animation.movie.res.CResourceManager",
    "com.live2d.cubism.doc.animation.movie.track.CMvEffectManager",
    "com.live2d.cubism.doc.animation.movie.track.CMvTrack_Group_Source",
    "com.live2d.cubism.doc.animation.movie.track.CMvTrack_Live2DModel_Source",
    "com.live2d.cubism.doc.animation.movie.track.ICMvTrack_Linked",
    "com.live2d.cubism.doc.animation.movie.track.ICMvTrack_Source",
    "com.live2d.cubism.doc.animation.movie.track.resource.ACResource_File",
    "com.live2d.cubism.doc.animation.movie.track.resource.CResource_Linked_Model",
    "com.live2d.cubism.doc.model.deformer.CTrackSourceSet",
    "com.live2d.cubism.doc.model.id.CAttrId",
    "com.live2d.cubism.doc.model.id.CEffectId",
    "com.live2d.cubism.doc.model.options.edition.EditorEdition",
    "com.live2d.graphics.CImageCanvas",
    "com.live2d.graphics3d.type.GRectF",
    "com.live2d.type.CColor",
    "com.live2d.type.CResourceGroupGuid",
    "com.live2d.type.CResourceGuid",
    "com.live2d.type.CSceneGuid",
    "com.live2d.type.CTrackGuid",
];
